name: Uniqlo Rare Discount Detector

on:
  schedule:
    - cron: "0 10-21 * * *"   # hourly, 12 runs/day (UTC)
  workflow_dispatch:

concurrency:
  group: uniqlo-scrape
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID_MUGE: ${{ secrets.TELEGRAM_CHAT_ID_MUGE }}
      TELEGRAM_CHAT_ID_BURAK: ${{ secrets.TELEGRAM_CHAT_ID_BURAK }}
      APP_ENV: prod

    steps:
      - name: Record start time
        run: |
          echo "JOB_START_TS=$(date +%s)" >> $GITHUB_ENV

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # --------------------------------------------------
      # Playwright
      # --------------------------------------------------
      - name: Install Playwright browsers
        run: |
          python -m playwright install chromium --with-deps

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libatk1.0-0 libx11-xcb1

      # ---------------------------------------------
      # Restore SQLite DB
      # ---------------------------------------------
#      - name: Restore SQLite database
#        env:
#          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          set -e
#          mkdir -p db
#          gh release download uniqlo-db-latest \
#            --pattern uniqlo.sqlite \
#            --output db/uniqlo.sqlite \
#            --clobber || echo "No existing DB found â€” starting fresh"

      # ---------------------------------------------
      # Orchestrator
      # ---------------------------------------------
      - name: Run orchestrator
        run: |
          python -m src.orchestrator
      # ---------------------------------------------
      # Persist DB
      # ---------------------------------------------
      - name: Publish SQLite snapshot
        uses: softprops/action-gh-release@v2
        with:
          tag_name: uniqlo-db-latest
          name: Uniqlo Sale SQLite (Latest)
          files: db/uniqlo.sqlite
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Record end time and duration
        if: always()
        run: |
          JOB_END_TS=$(date +%s)
          echo "JOB_END_TS=$JOB_END_TS" >> $GITHUB_ENV
          echo "JOB_DURATION_MIN=$(( (JOB_END_TS - JOB_START_TS) / 60 ))" >> $GITHUB_ENV
          echo "Job duration: $(( (JOB_END_TS - JOB_START_TS) / 60 )) minutes"